spring:
  application:
    name: chatroom
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true




