server:
  port: 8081

debug: true

websocket:
  netty:
    ip: 0.0.0.0
    port: 1024
    path: /ws
    maxFrameSize: 65536
    readerIdleTimeSeconds: 3
    writerIdleTimeSeconds: 0
    allIdleTimeSeconds: 0

spring:
  redis:
    host: 127.0.0.1
    port: 32379
    password:
    database: 11

  rocketmq:
    namesrvAddr:
    producerGroup:
    retryTimesWhenSendFailed: 2
    producerTopic: websocket-inbound-topic-dev
    consumerTopic: websocket-outbound-topic-dev
