server:
  port: 8081

debug: true

websocket:
  netty:
    ip: 0.0.0.0
    port: 1024
    path: /ws
    maxFrameSize: 65536
    readerIdleTimeSeconds: 3
    writerIdleTimeSeconds: 0
    allIdleTimeSeconds: 0

spring:
  cloud:
    ##RocketMQ配置
    stream:
      rocketmq:
        bindings:
          talentEnterpriseOutput:
            producer:
              group: talent-enterprise-output-group-dev
              sync: true
          updateEnterpriseInput:
            consumer:
              orderly: false
              tags: update_enterprise
          updateTalentEnterpriseInput:
            consumer:
              orderly: false
              tags: update_talent_enterprise
          enterpriseStatisticInput:
            consumer:
              orderly: false
              tags: enterprise_statistic
        binder:
          name-server: 192.168.1.241:9876
      bindings:
        updateEnterpriseInput:
          destination: talent-enterprise-topic-dev
          group: update-enterprise-input-group-dev
          content-type: application/json
          consumer:
            concurrency: 5
        updateTalentEnterpriseInput:
          destination: talent-enterprise-topic-dev
          content-type: application/json
          group: update-talent-enterprise-input-group-dev
          consumer:
            concurrency: 5
        enterpriseStatisticInput:
          destination: talent-enterprise-topic-dev
          content-type: application/json
          group: enterprise-statistic-input-group-dev
          consumer:
            concurrency: 5
        talentEnterpriseOutput:
          destination: talent-enterprise-topic-dev
          content-type: application/json

  redis:
    host: 47.97.186.99
    port: 6380
    password: Test123456
    database: 11
