server:
  port: 8081

debug: true

websocket:
  netty:
    ip: 0.0.0.0
    port: 1024
    path: /ws
    maxFrameSize: 65536
    readerIdleTimeSeconds: 20
    writerIdleTimeSeconds: 0
    allIdleTimeSeconds: 0

spring:
  redis:
    host: r-bp1sf7zphr3ercyvw4.redis.rds.aliyuncs.com
    port: 6379
    password: YC3p#JTuC6m7
    database: 7

  rocketmq:
    namesrvAddr: 192.168.1.8:30876
    producerGroup: websocket-producer-group-dev
    consumerGroup: websocket-consumer-group-dev
    retryTimesWhenSendFailed: 2
    producerTopic: websocket-inbound-topic-dev
    consumerTopic: websocket-outbound-topic-dev
    consumeMessageBatchMaxSize: 10
